Update prodVirginia.yml

diff --git a/.github/workflows/prodVirginia.yml b/.github/workflows/prodVirginia.yml
--- a/.github/workflows/prodVirginia.yml
+++ b/.github/workflows/prodVirginia.yml
@@ -35,14 +35,28 @@ jobs:
         ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
         IMAGE_TAG: ${{ github.sha }}
       run: |
-        # Build a docker container and
-        # push it to ECR so that it can
-        # be deployed to ECS.
+        if [ -z "$ECR_REGISTRY" ]; then
+          echo "ERROR: ECR_REGISTRY está vacío"
+          exit 1
+        fi
+    
+        if [ -z "$ECR_REPOSITORY" ]; then
+          echo "ERROR: ECR_REPOSITORY está vacío"
+          exit 1
+        fi
+    
+        echo "Building Docker image..."
         docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile .
+    
+        echo "Tagging latest image..."
         docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
+    
+        echo "Pushing Docker image to ECR..."
         docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
         docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
+    
         echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
+    
 
     - name: Fill in the new image ID in the Amazon ECS task definition
       id: task-def
